hyperaudio/hyperaudio-lite

- js/hyperaudio-lite.js
This should address https://github.com/hyperaudio/hyperaudio-lite/issues/24
Also if for some reason Velocity is not detected we skip the call instead of breaking.
> 24 detects if Velocity has been placed on the jQuery object

- js/hyperaudio-lite.js
Fixing a bug found for the Velocity/JQuery incompatibility issue.
> fix for jQuery compatibility

- js/hyperaudio-lite.js
Should fix https://github.com/hyperaudio/hyperaudio-lite/issues/29
> 29 mobile social share

- index.html
- js/hyperaudio-lite.js
This addresses https://github.com/hyperaudio/hyperaudio-lite/issues/27
> 27 autoscroll init

- js/hyperaudio-lite.js
two new methods added:
- `toggleAutoScroll()`
- `setAutoScroll(Boolean)`
> 34 added hooks to turn autoscroll on/off

- index.html
- js/caption.js
Should address https://github.com/hyperaudio/hyperaudio-lite/issues/36
> 36 added caption generation

- index.html
this addresses issue https://github.com/hyperaudio/hyperaudio-lite/issues/40 but does not fix.
> 40 remove default attribute from track

- index.html
should fix https://github.com/hyperaudio/hyperaudio-lite/issues/42
> 42 - quick fix for incorrect mime type in example

- __TEST__/hyperaudio-lite.test.js
- package-lock.json
- package.json
addresses https://github.com/hyperaudio/hyperaudio-lite/issues/52
> 52 updated jest and added dom environment to test

- js/hyperaudio-lite.js
This addresses https://github.com/hyperaudio/hyperaudio-lite/issues/55
> 55 class active remove

- __TEST__/hyperaudio-lite.test.js
> 57 updated  tests

- __TEST__/hyperaudio-lite.test.js
looks like we have actual tests now :)
> 57 actual tests

- js/hyperaudio-lite.js
Various issues with SoundCloud resolved:
- getPosition calls `getStatus` *after* `currentTime` is returned
- call to `this.playerType` was mistakenly referenced as`playerType`
> Fix for #69 and #70

- js/hyperaudio-lite.js
addresses https://github.com/hyperaudio/hyperaudio-lite/issues/75
> 75 payment pointer intermittent bug

- js/caption.js
> 87 srt index fix

- js/caption.js
We also changed the method of caption insertion to better work with Firefox and avoid race conditions in general.
> changes to caption generation to allow for words without duration

- __TEST__/hyperaudio-lite.test.js
addresses https://github.com/hyperaudio/hyperaudio-lite/issues/103
> 103 fix failing test

- js/hyperaudio-lite.js
Fixes https://github.com/hyperaudio/hyperaudio-lite/issues/105
> fix for undefined element

- js/caption.js
patch for stray video reference
> 113 captions no video bug

- js/hyperaudio-lite.js
more flexibility in adding new data sources through the new interface and options list
> strategyPlayer interface and options

- index.html
- js/hyperaudio-lite.js
This should add the required option.
> 124 play on click option

- js/hyperaudio-lite.js
- videojs.html
Adds Brightcove / VideoJS compatibility, addressing #130
> 130 videojs bc

- js/hyperaudio-lite.js
> players cleanup #132

- js/hyperaudio-lite-extension.js
addresses #127 – although no bugs were found
> modern JS #127

- __TEST__/hyperaudio-lite.test.js
- index.html
- js/hyperaudio-lite.js
Addresses #137 
Note that the `data-media-src` and `data-media-type` attributes can be placed on any element within the transcript, although `section` is recommended.
> 137 src in section

- js/hyperaudio-lite.js
> Hotfix media src changes

- __TEST__/hyperaudio-lite.test.js
- index.html
- js/hyperaudio-lite.js
> refinement for section src

- js/caption.js
> caption optimisation

- js/hyperaudio-lite.js
> more robust treatment of text selection

- js/hyperaudio-lite.js
Even more robust treatment of text selection, now checks if selection is within the transcript.
> 150 fragment selection

- js/hyperaudio-lite.js
> flag omission of data-player-type

- js/caption.js
> updated version of caption.js

- js/hyperaudio-lite.js
> 199 selection range fix

- __TEST__/hyperaudio-lite.test.js
- js/hyperaudio-lite.js
- package.json
big refactor and selection fixes
> initial refactor

- js/hyperaudio-lite.js
This is a belt and braces check for users that have disabled the popover selection functionality.
> popover check

- js/hyperaudio-lite.js
> 207 fix autoscroll
